spring:
  application:
    name: account-service  # 服务名称

  config:
    import: "configserver:http://localhost:8888"
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    config:
      uri: http://localhost:8888

  kafka:
    bootstrap-servers: localhost:9092  # Kafka 服务器地址

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL 日志，方便查看

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有 Actuator 端点，生产环境可按需调整
