server:
  port: 8888
spring:
  application:
    name: config-service  # 服务名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/shallow-and-cat/fx.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


