server:
  port: 9010
spring:
  application:
    name: flask-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 10000ms
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
